# Generated by Django 5.2.6 on 2025-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En Revisión')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
