# Generated by Django 5.2.6 on 2025-10-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('auditoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AportacionPE',
            fields=[
                ('aportacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='aportaciones_pe', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademica',
            fields=[
                ('gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion_id', models.ForeignKey(db_column='institucion_id', on_delete=django.db.models.deletion.PROTECT, related_name='gestion_academica', to='core.institucion')),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='gestion_academica', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('hallazgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_hallazgo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('es_indice_rendimiento', models.BooleanField(default=False)),
                ('indicador_mr2025', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe_id', models.ForeignKey(blank=True, db_column='atributo_pe_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='gestion_academica.atributope')),
                ('objetivo_id', models.ForeignKey(blank=True, db_column='objetivo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='gestion_academica.objetivoeducacional')),
                ('programa_id', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='core.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='AccionMejora',
            fields=[
                ('accion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('meta', models.TextField()),
                ('fecha_meta', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hallazgo_id', models.ForeignKey(db_column='hallazgo_id', on_delete=django.db.models.deletion.PROTECT, related_name='acciones_mejora', to='evaluacion_acreditacion.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('indicador_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterio_id', models.ForeignKey(db_column='criterio_id', on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='gestion_academica.criteriodesempeno')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionIndicador',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_seccion', models.CharField(max_length=50)),
                ('instrumento_evaluacion', models.CharField(max_length=100)),
                ('descripcion_instrumento', models.TextField(blank=True, null=True)),
                ('periodo_evaluacion', models.CharField(max_length=50)),
                ('valoracion', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('analisis_resultados', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='core.curso')),
                ('indicador_id', models.ForeignKey(db_column='indicador_id', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluacion_acreditacion.indicador')),
            ],
        ),
    ]
