# Generated by Django 5.2.6 on 2025-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionMejora',
            fields=[
                ('accion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('meta', models.TextField()),
                ('fecha_meta', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
