# Generated by Django 5.2.6 on 2025-11-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AportacionPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hallazgo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('es_indice_rendimiento', models.BooleanField(default=False)),
                ('indicador_mr2025', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='AccionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('meta', models.TextField()),
                ('fecha_meta', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.criteriodesempeno')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_seccion', models.CharField(max_length=50)),
                ('instrumento_evaluacion', models.CharField(max_length=100)),
                ('descripcion_instrumento', models.TextField(blank=True, null=True)),
                ('periodo_evaluacion', models.CharField(max_length=50)),
                ('valoracion', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('analisis_resultados', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.indicador')),
            ],
        ),
    ]
