# Generated by Django 5.2.6 on 2025-09-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('indicador_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
