# Generated by Django 5.2.6 on 2025-09-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_acreditacion', '0002_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion_Indicador',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_seccion', models.CharField(max_length=50)),
                ('instrumento_evaluacion', models.CharField(max_length=100)),
                ('descripcion_instrumento', models.TextField()),
                ('periodo_evaluacion', models.CharField(max_length=50)),
                ('valoracion', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('analisis_resultados', models.TextField()),
                ('meta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
