# Generated by Django 5.2.6 on 2025-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_acreditacion', '0003_evaluacion_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='aportacion_pe',
            fields=[
                ('aportacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('auditoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Academica',
            fields=[
                ('gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('hallazgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_hallazgo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('objetivo_id', models.IntegerField()),
                ('atributo_pe_id', models.IntegerField()),
                ('es_indice_rendimiento', models.BooleanField()),
                ('indicador_mr2025', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
