# Generated by Django 5.2.6 on 2025-11-10 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('organizacion_curricular', 'Organización Curricular')], default='organizacion_curricular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.periodo')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='CursoObligatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoOptativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
    ]
