# Generated by Django 5.2.6 on 2025-11-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('evaluacion_acreditacion', '0001_initial'),
        ('gestion_academica', '0001_initial'),
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético'), ('plan_mejora', 'Plan de Mejora'), ('valoracion_objetivos', 'Valoración de Objetivos')], default='organizacion_curricular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.periodo')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocenteCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.capacitaciondocente')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoObjetivoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='AportacionPECedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aportacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.aportacionpe')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionDisciplinarCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.actualizaciondisciplinar')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='AccionMejoraCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.accionmejora')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioDesempenoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.criteriodesempeno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoObligatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoOptativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionIndicadorCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.evaluacionindicador')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDisenoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciadiseno')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesionalCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciaprofesional')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademicaCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.formacionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademicaCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.gestionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.criteriodesempeno')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='LogroProfesionalCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.logroprofesional')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEducacionalCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionOrganizacionesCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.participacionorganizaciones')),
            ],
        ),
        migrations.CreateModel(
            name='PremioDistincionCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.premiodistincion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademicoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.productoacademico')),
            ],
        ),
    ]
