# Generated by Django 5.2.6 on 2025-11-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='tipo',
            field=models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético')], default='organizacion_curricular', max_length=50),
        ),
    ]
