# Generated by Django 5.2.6 on 2025-11-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0001_initial'),
        ('core', '0002_alter_curso_tipo'),
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCurricularEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eje', models.CharField(max_length=50)),
                ('horas', models.PositiveIntegerField()),
                ('curso_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursocurricular')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CursoObligatorioEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eje', models.CharField(max_length=50)),
                ('horas', models.PositiveIntegerField()),
                ('curso_obligatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursoobligatorio')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CursoOptativoEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eje', models.CharField(max_length=50)),
                ('horas', models.PositiveIntegerField()),
                ('curso_optativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursooptativo')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento')),
            ],
        ),
    ]
