# Generated by Django 5.2.6 on 2025-11-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0001_initial'),
        ('core', '0001_initial'),
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='tipo',
            field=models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético'), ('plan_mejora', 'Plan de Mejora'), ('valoracion_objetivos', 'Valoración de Objetivos'), ('aep_vs_aecacei', 'AEP vs AE-CACEI'), ('aep_vs_oe', 'AEP vs OE'), ('cursos_vs_aep', 'Cursos vs AEP')], default='organizacion_curricular', max_length=50),
        ),
        migrations.CreateModel(
            name='CursoAtributoPECedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.cursoatributope')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
    ]
