# Generated by Django 5.2.6 on 2025-11-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cedulas', '0001_initial'),
        ('core', '0001_initial'),
        ('evaluacion_acreditacion', '0001_initial'),
        ('gestion_academica', '0001_initial'),
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionmejoracedula',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.accionmejora'),
        ),
        migrations.AddField(
            model_name='accionmejoracedula',
            name='hallazgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo'),
        ),
        migrations.AddField(
            model_name='actualizaciondisciplinarcedula',
            name='actualizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.actualizaciondisciplinar'),
        ),
        migrations.AddField(
            model_name='aportacionpecedula',
            name='aportacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.aportacionpe'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedula',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedula',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedulaaepvsoe',
            name='atributo_pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedulaaepvsoe',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedulaaepvsoe',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributopeobjetivo'),
        ),
        migrations.AddField(
            model_name='atributopecaceicedula',
            name='atributo_cacei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributocacei'),
        ),
        migrations.AddField(
            model_name='atributopecaceicedula',
            name='atributo_pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='atributopecaceicedula',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributopecacei'),
        ),
        migrations.AddField(
            model_name='atributopecedula',
            name='atributo_pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='bibliografiacedula',
            name='bibliografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.bibliografia'),
        ),
        migrations.AddField(
            model_name='capacitaciondocentecedula',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.capacitaciondocente'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.periodo'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.programaeducativo'),
        ),
        migrations.AddField(
            model_name='capacitaciondocentecedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='bibliografiacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='atributopecedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='atributopecaceicedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedulaaepvsoe',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='atributoobjetivocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='aportacionpecedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='actualizaciondisciplinarcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='accionmejoracedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='criteriodesempenocedula',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='criteriodesempenocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='criteriodesempenocedula',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.criteriodesempeno'),
        ),
        migrations.AddField(
            model_name='cursoatributopecedula',
            name='atributo_pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.atributope'),
        ),
        migrations.AddField(
            model_name='cursoatributopecedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoatributopecedula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='cursoatributopecedula',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.cursoatributope'),
        ),
        migrations.AddField(
            model_name='cursocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursocedula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='cursocurricular',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursocurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='cursocurriculareje',
            name='curso_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursocurricular'),
        ),
        migrations.AddField(
            model_name='cursocurriculareje',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento'),
        ),
        migrations.AddField(
            model_name='cursoejecedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoejecedula',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento'),
        ),
        migrations.AddField(
            model_name='cursoestadisticascedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoinfocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoobjetivoespecificocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoobjetivoespecificocedula',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoespecifico'),
        ),
        migrations.AddField(
            model_name='cursoobligatorio',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursoobligatorio',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='cursoobligatorioeje',
            name='curso_obligatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursoobligatorio'),
        ),
        migrations.AddField(
            model_name='cursoobligatorioeje',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento'),
        ),
        migrations.AddField(
            model_name='cursooptativo',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='cursooptativo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='cursooptativoeje',
            name='curso_optativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cursooptativo'),
        ),
        migrations.AddField(
            model_name='cursooptativoeje',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.ejeconocimiento'),
        ),
        migrations.AddField(
            model_name='estrategiaensenanzacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='estrategiaevaluacioncedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='evaluacionindicadorcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='evaluacionindicadorcedula',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.evaluacionindicador'),
        ),
        migrations.AddField(
            model_name='evaluacionindicadorcedula',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.indicador'),
        ),
        migrations.AddField(
            model_name='experienciadisenocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='experienciadisenocedula',
            name='experiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciadiseno'),
        ),
        migrations.AddField(
            model_name='experienciaprofesionalcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='experienciaprofesionalcedula',
            name='experiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciaprofesional'),
        ),
        migrations.AddField(
            model_name='formacionacademicacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='formacionacademicacedula',
            name='formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.formacionacademica'),
        ),
        migrations.AddField(
            model_name='gestionacademicacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='gestionacademicacedula',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.gestionacademica'),
        ),
        migrations.AddField(
            model_name='hallazgocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='hallazgocedula',
            name='hallazgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo'),
        ),
        migrations.AddField(
            model_name='horassemanacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='indicadorcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='indicadorcedula',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.criteriodesempeno'),
        ),
        migrations.AddField(
            model_name='indicadorcedula',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.indicador'),
        ),
        migrations.AddField(
            model_name='logroprofesionalcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='logroprofesionalcedula',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.logroprofesional'),
        ),
        migrations.AddField(
            model_name='objetivoeducacionalcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='objetivoeducacionalcedula',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.objetivoeducacional'),
        ),
        migrations.AddField(
            model_name='participacionorganizacionescedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='participacionorganizacionescedula',
            name='participacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.participacionorganizaciones'),
        ),
        migrations.AddField(
            model_name='practicacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='premiodistincioncedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='premiodistincioncedula',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.premiodistincion'),
        ),
        migrations.AddField(
            model_name='productoacademicocedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='productoacademicocedula',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.productoacademico'),
        ),
        migrations.AddField(
            model_name='profesoractualcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='profesoractualcedula',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.AddField(
            model_name='profesoranteriorcedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
        migrations.AddField(
            model_name='profesoranteriorcedula',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.AddField(
            model_name='unidadtematicacedula',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula'),
        ),
    ]
