# Generated by Django 5.2.6 on 2025-11-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0002_cedula_profesor_alter_cedula_tipo'),
        ('evaluacion_acreditacion', '0001_initial'),
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDisciplinarCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.actualizaciondisciplinar')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='AportacionPECedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aportacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.aportacionpe')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocenteCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.capacitaciondocente')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDisenoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciadiseno')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesionalCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.experienciaprofesional')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademicaCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.formacionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademicaCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.gestionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='LogroProfesionalCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.logroprofesional')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionOrganizacionesCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.participacionorganizaciones')),
            ],
        ),
        migrations.CreateModel(
            name='PremioDistincionCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.premiodistincion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademicoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_profesores.productoacademico')),
            ],
        ),
    ]
