# Generated by Django 5.2.6 on 2025-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0002_alter_cedula_tipo_cursoatributopecedula_cursocedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='tipo',
            field=models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético'), ('plan_mejora', 'Plan de Mejora'), ('valoracion_objetivos', 'Valoración de Objetivos'), ('aep_vs_aecacei', 'AEP vs AE-CACEI'), ('aep_vs_oe', 'AEP vs OE'), ('cursos_vs_aep', 'Cursos vs AEP'), ('valoracion_herramientas_atributos', 'Valoración de Herramientas de los Atributos')], default='organizacion_curricular', max_length=50),
        ),
    ]
