# Generated by Django 5.2.6 on 2025-11-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0003_alter_cedula_tipo_atributoobjetivocedulaaepvsoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributoobjetivocedulaaepvsoe',
            old_name='atributo',
            new_name='atributo_pe',
        ),
    ]
