# Generated by Django 5.2.6 on 2025-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0003_alter_cedula_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='tipo',
            field=models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético'), ('plan_mejora', 'Plan de Mejora'), ('valoracion_objetivos', 'Valoración de Objetivos'), ('aep_vs_aecacei', 'AEP vs AE-CACEI'), ('aep_vs_oe', 'AEP vs OE'), ('cursos_vs_aep', 'Cursos vs AEP'), ('herramientas_valoracion_aep', 'Herramientas de Valoración de AEP')], default='organizacion_curricular', max_length=50),
        ),
    ]
