# Generated by Django 5.2.6 on 2025-11-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0003_actualizaciondisciplinarcedula_aportacionpecedula_and_more'),
        ('evaluacion_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='tipo',
            field=models.CharField(choices=[('organizacion_curricular', 'Organización Curricular'), ('cv_sintetico', 'CV Sintético'), ('plan_mejora', 'Plan de Mejora')], default='organizacion_curricular', max_length=50),
        ),
        migrations.CreateModel(
            name='AccionMejoraCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.accionmejora')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoCedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cedulas.cedula')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion_acreditacion.hallazgo')),
            ],
        ),
    ]
