# Generated by Django 5.2.6 on 2025-09-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoCACEI',
            fields=[
                ('atributo_cacei_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('wk_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtributoPE',
            fields=[
                ('atributo_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_abreviado', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('seriacion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], default='obligatorio', max_length=50)),
                ('horas_totales', models.IntegerField()),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjeConocimiento',
            fields=[
                ('eje_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación'), ('proyecto', 'Proyecto'), ('patente', 'Patente'), ('otro', 'Otro')], default='publicacion', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En Revisión')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriterioDesempeno',
            fields=[
                ('criterio_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe', models.ForeignKey(db_column='atributo_pe_id', on_delete=django.db.models.deletion.PROTECT, related_name='criterios_desempeno', to='gestion_academica.atributope')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('bibliografia_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=100)),
                ('anio_publicacion', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='bibliografias', to='gestion_academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaEnsenanza',
            fields=[
                ('estrategia_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='estrategias_ensenanza', to='gestion_academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaEvaluacion',
            fields=[
                ('estrategia_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='estrategias_evaluacion', to='gestion_academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='HorasSemana',
            fields=[
                ('horas_id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_totales', models.PositiveSmallIntegerField()),
                ('horas_aula', models.PositiveSmallIntegerField()),
                ('horas_laboratorio', models.PositiveSmallIntegerField()),
                ('horas_practicas', models.PositiveSmallIntegerField()),
                ('numero_grupos', models.PositiveSmallIntegerField()),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('porcentaje_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_reprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='horas_semana', to='gestion_academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_especificos', to='gestion_academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEducacional',
            fields=[
                ('objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_educacionales', to='gestion_academica.programaeducativo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='gestion_academica.programaeducativo'),
        ),
        migrations.AddField(
            model_name='atributope',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='atributos_pe', to='gestion_academica.programaeducativo'),
        ),
        migrations.CreateModel(
            name='UnidadTematica',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='unidades_tematicas', to='gestion_academica.curso')),
            ],
        ),
    ]
