# Generated by Django 5.2.6 on 2025-10-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('practica_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='core.curso')),
            ],
        ),
    ]
