# Generated by Django 5.2.6 on 2025-09-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('seriacion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], default='obligatorio', max_length=50)),
                ('horas_totales', models.IntegerField()),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
