# Generated by Django 5.2.6 on 2025-10-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='gestion_academica.alumno')),
                ('profesor_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='gestion_de_profesores.profesorcurso')),
            ],
        ),
    ]
