# Generated by Django 5.2.6 on 2025-09-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoAcademico',
        ),
    ]
