# Generated by Django 5.2.6 on 2025-10-31 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_alumno_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='valor',
            field=models.PositiveSmallIntegerField(help_text='Calificación del alumno entre 0 y 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
