# Generated by Django 5.2.6 on 2025-09-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_delete_productoacademico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributope',
            old_name='programa',
            new_name='programa_id',
        ),
        migrations.RenameField(
            model_name='bibliografia',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='criteriodesempeno',
            old_name='atributo_pe',
            new_name='atributo_pe_id',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='programa',
            new_name='programa_id',
        ),
        migrations.RenameField(
            model_name='estrategiaensenanza',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='estrategiaevaluacion',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='horassemana',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='objetivoeducacional',
            old_name='programa',
            new_name='programa_id',
        ),
        migrations.RenameField(
            model_name='objetivoespecifico',
            old_name='curso',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='unidadtematica',
            old_name='curso',
            new_name='curso_id',
        ),
    ]
