# Generated by Django 5.2.6 on 2025-09-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_rename_programa_atributope_programa_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoPECACEI',
            fields=[
                ('atributo_pe_cacei_id', models.AutoField(primary_key=True, serialize=False)),
                ('justificacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_cacei_id', models.ForeignKey(db_column='atributo_cacei_id', on_delete=django.db.models.deletion.PROTECT, related_name='atributo_pe_cacei', to='gestion_academica.atributocacei')),
                ('atributo_pe_id', models.ForeignKey(db_column='atributo_pe_id', on_delete=django.db.models.deletion.PROTECT, related_name='atributo_pe_cacei', to='gestion_academica.atributope')),
            ],
        ),
        migrations.AddField(
            model_name='atributope',
            name='atributos_cacei',
            field=models.ManyToManyField(through='gestion_academica.AtributoPECACEI', to='gestion_academica.atributocacei'),
        ),
        migrations.CreateModel(
            name='AtributoPEObjetivo',
            fields=[
                ('atributo_pe_objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('justificacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe_id', models.ForeignKey(db_column='atributo_pe_id', on_delete=django.db.models.deletion.PROTECT, related_name='atributo_pe_objetivo', to='gestion_academica.atributope')),
                ('objetivo_id', models.ForeignKey(db_column='objetivo_id', on_delete=django.db.models.deletion.PROTECT, related_name='atributo_pe_objetivo', to='gestion_academica.objetivoeducacional')),
            ],
        ),
        migrations.AddField(
            model_name='atributope',
            name='objetivos_educacionales',
            field=models.ManyToManyField(through='gestion_academica.AtributoPEObjetivo', to='gestion_academica.objetivoeducacional'),
        ),
        migrations.CreateModel(
            name='CursoAtributoPE',
            fields=[
                ('curso_atributo_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_aporte', models.CharField(choices=[('I', 'Introductorio'), ('M', 'Medio'), ('A', 'Avanzado')], default='I', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_pe_id', models.ForeignKey(db_column='atributo_pe_id', on_delete=django.db.models.deletion.PROTECT, related_name='curso_atributo_pe', to='gestion_academica.atributope')),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='curso_atributo_pe', to='gestion_academica.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='atributos_pe',
            field=models.ManyToManyField(through='gestion_academica.CursoAtributoPE', to='gestion_academica.atributope'),
        ),
        migrations.CreateModel(
            name='CursoEje',
            fields=[
                ('curso_eje_id', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='curso_eje', to='gestion_academica.curso')),
                ('eje_id', models.ForeignKey(db_column='eje_id', on_delete=django.db.models.deletion.PROTECT, related_name='curso_eje', to='gestion_academica.ejeconocimiento')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='ejes_conocimiento',
            field=models.ManyToManyField(through='gestion_academica.CursoEje', to='gestion_academica.ejeconocimiento'),
        ),
    ]
