# Generated by Django 5.2.6 on 2025-09-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_estrategiaensenanza'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiaEvaluacion',
            fields=[
                ('estrategia_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
