# Generated by Django 5.2.6 on 2025-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_estrategiaevaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEducacional',
            fields=[
                ('objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
