# Generated by Django 5.2.6 on 2025-09-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_bibliografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasSemana',
            fields=[
                ('horas_id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_totales', models.PositiveSmallIntegerField()),
                ('horas_aula', models.PositiveSmallIntegerField()),
                ('horas_laboratorio', models.PositiveSmallIntegerField()),
                ('horas_practicas', models.PositiveSmallIntegerField()),
                ('numero_grupos', models.PositiveSmallIntegerField()),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('porcentaje_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_reprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
