# Generated by Django 5.2.6 on 2025-09-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_horassemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación'), ('proyecto', 'Proyecto'), ('patente', 'Patente'), ('otro', 'Otro')], default='publicacion', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
