# Generated by Django 5.2.6 on 2025-09-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_productoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjeConocimiento',
            fields=[
                ('eje_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
