# Generated by Django 5.2.6 on 2025-09-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0009_ejeconocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('objetivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
