# Generated by Django 5.2.6 on 2025-09-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0010_objetivoespecifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoPE',
            fields=[
                ('atributo_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_abreviado', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
