# Generated by Django 5.2.6 on 2025-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('practica_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
