# Generated by Django 5.2.6 on 2025-09-26 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academica', '0002_delete_productoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('practica_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='gestion_academica.curso')),
            ],
        ),
    ]
