# Generated by Django 5.2.6 on 2025-11-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('horas', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('horas', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('nivel_experiencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actividades', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('especialidad', 'Especialidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='licenciatura', max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='LogroProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevancia', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionOrganizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('nivel_participacion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='PremioDistincion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion_otorga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación'), ('proyecto', 'Proyecto'), ('patente', 'Patente'), ('otro', 'Otro')], default='publicacion', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('responsable', 'Responsable'), ('instructor', 'Instructor')], default='responsable', max_length=20)),
                ('periodo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
    ]
