# Generated by Django 5.2.6 on 2025-10-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDisciplinar',
            fields=[
                ('actualizacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('horas', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='actualizacion_disciplinar', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocente',
            fields=[
                ('capacitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('horas', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_docente', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDiseno',
            fields=[
                ('diseno_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizacion', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('nivel_experiencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='experiencia_disenio', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('experiencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizacion', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actividades', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='experiencia_profesional', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('formacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('especialidad', 'Especialidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='licenciatura', max_length=20)),
                ('institucion', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('anio_obtencion', models.PositiveSmallIntegerField()),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='formacion_academica', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='LogroProfesional',
            fields=[
                ('logro_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevancia', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='logros_profesionales', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionOrganizaciones',
            fields=[
                ('participacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizacion', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('nivel_participacion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_organizaciones', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='PremioDistincion',
            fields=[
                ('premio_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('institucion_otorga', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='premios_distinciones', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación'), ('proyecto', 'Proyecto'), ('patente', 'Patente'), ('otro', 'Otro')], default='publicacion', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos_academicos', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('profesor_curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('responsable', 'Responsable'), ('instructor', 'Instructor')], default='responsable', max_length=20)),
                ('periodo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='core.curso')),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.profesor')),
            ],
        ),
    ]
