# Generated by Django 5.2.6 on 2025-09-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación'), ('proyecto', 'Proyecto'), ('patente', 'Patente'), ('otro', 'Otro')], default='publicacion', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_id', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos_academicos', to='gestion_de_profesores.profesor')),
            ],
        ),
    ]
