# Generated by Django 5.2.6 on 2025-10-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gestion_de_profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesorcurso',
            name='curso_id',
            field=models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.PROTECT, related_name='profesores_cursos', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='profesorcurso',
            name='profesor_id',
            field=models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.PROTECT, related_name='profesores_cursos', to='core.profesor'),
        ),
    ]
