# Generated by Django 5.2.6 on 2025-10-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nombramiento_actual', models.CharField(max_length=100)),
                ('antiguedad', models.PositiveSmallIntegerField()),
                ('experiencia_ingenieria', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En Revisión')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('seriacion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], default='obligatorio', max_length=50)),
                ('horas_totales', models.IntegerField()),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa_id', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.programaeducativo')),
            ],
        ),
    ]
