# Generated by Django 5.2.6 on 2025-11-28 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado si el profesor tiene acceso al sistema como docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.programaeducativo'),
        ),
    ]
