# Generated by Django 5.2.6 on 2025-11-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo'), ('curricular', 'Curricular')], default='obligatorio', max_length=50),
        ),
    ]
